### ISSUE TITLE
Guardar trazabilidad de los que intervienen ( quien y fecha) en la aprobación de cumplidos.

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/cumplidos_cliente#10]
Se requiere guardar la trazabilidad de la aprobación de los cumplidos mensuales, ya que actualmente se remplaza el registro de la persona que realizó la aprobación, por lo tanto no se sabe quien fue la anterior persona en aprobar.

para ello se necesita realizar lo siguiente:

- [x] identificar en el cliente en que sección se realiza la acción de aprobación. 

- [x] identificar en la respectiva api donde se realiza las modificaciones. 

- [x] hacer una reconstrucción del modelo relacional de las tablas afectadas. 

- [x] proponer uno o varios modelos para solucionar el problema de la trazabilidad , estos han de ser evaluados para pasar a su aprobación

***calidad***

- [x] modelos evaluados por el equipo de **Entregables**. 

- [x] modelos fueron evaluados por arquitectos, soporte y DBA. 

- [ ] modelos fueron aprobados
_______________________________________________________________________________
Modelo de BD final: 
![udistrital_core_db](https://user-images.githubusercontent.com/29903400/65236273-d92f7f00-da9d-11e9-9b47-7db3a3ba334b.png)

[modelo de base de datos pago mensual.dbm.zip](https://github.com/udistrital/cumplidos_cliente/files/3632340/modelo.de.base.de.datos.pago.mensual.dbm.zip)

[udistrital_core_db.sql.zip](https://github.com/udistrital/cumplidos_cliente/files/3632542/udistrital_core_db.sql.zip)

**Comment by anlramirezs11** [comment]
09/09/2019
Se configuran las variables de entorno 
![image](https://user-images.githubusercontent.com/29903400/64557103-7a803d80-d306-11e9-93bb-6781f36c12d3.png)

, se identifican las API que a la fecha siguen sin poder ser usadas:
* FINANCIERA_MID_SERVICE
* OIKOS_AMAZON_SERVICE
* PAGOS_SERVICE
* TITAN_SERVICE
* SICAPITAL_SERVICE

**Comment by anlramirezs11** [comment]
10/09/2019

Se realiza una segunda revisión de APIs para correr el cliente: 

- [ ] WSO2_SERVICE

- [ ] ACADEMICA_SERVICE

- [ ] ACADEMICA_WSO_SERVICE

- [ ] ADMINISTRATIVA_MID_SERVICE

- [ ] ADMINISTRATIVA_SERVICE

- [ ] ADMINISTRATIVA_PRUEBAS_SERVICE

- [ ] ARKA_SERVICE

- [ ] CONFIGURACION_SERVICE

- [ ] CORE_SERVICE

- [ ] CORE_AMAZON_SERVICE

- [ ] FINANCIERA_MID_SERVICE

- [ ] FINANCIERA_SERVICE

- [ ] MODELS_SERVICE

- [ ] NOTIFICACION_WS

- [ ] OIKOS_SERVICE

- [ ] OIKOS_AMAZON_SERVICE

- [ ] PAGOS_SERVICE

- [ ] TITAN_SERVICE

- [ ] SICAPITAL_SERVICE

- [ ] CONTRATO_SERVICE

- [ ] NUXEO_SERVICE

- [ ] HOMOLOGACION_SERVICE

**Comment by anlramirezs11** [comment]
Al intentar correr el cliente se encuentra un posible error de notificaciones: 
![image](https://user-images.githubusercontent.com/29903400/64634138-35214600-d3c2-11e9-9655-9c6c30c534d0.png)

Hablar con @fabianLeon y @FredyRodriguezR para solucionar el error.

**Comment by anlramirezs11** [comment]
El api donde se aprueba el pago a un contratista se hace en administrativa_crud -> PagoMensualController, el modelo que se usa en este controlador es: 
![image](https://user-images.githubusercontent.com/29903400/64635541-84b54100-d3c5-11e9-90e0-c993eb3ed803.png)

**Comment by anlramirezs11** [comment]
Se realiza un flujo básico para entender como funciona actualmente  la trazabilidad de los que intervienen.
![Diagrama en blanco](https://user-images.githubusercontent.com/29903400/64637644-dbbd1500-d3c9-11e9-8c2b-75f62725156d.png)

**Comment by anlramirezs11** [comment]
Instalar PgModeler para reconstruir el diseño de la base de datos y plantear una solución a la trazabilidad. 

https://github.com/udistrital/introduccion_oas/blob/master/instalacion_de_herramientas/pgmodeler_debian.md

**Comment by anlramirezs11** [comment]
![image](https://user-images.githubusercontent.com/29903400/64931936-44a8f080-d801-11e9-8910-456c939679bb.png)

**Comment by anlramirezs11** [comment]
17/10/2019.
Se editan los cambios de los nombres de la tabla y campos. Además se cambio el tipo de variable a varchar para los que son id.
![image](https://user-images.githubusercontent.com/29903400/65157614-9b2b5000-d9f6-11e9-91ea-533da6438daf.png)

Se procede a leer documentación para aplicar los linamientos de la oficina en el modelo plantado. Como lo sugiere el Ingeniero Jairo en el Issue #11
