### ISSUE TITLE
Análisis para la propuesta de trabajo.

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/cumplidos_cliente#109]
Analizar la propuesta generada para modulos y actividades a desarrollar en esta fase, asi como asignar prioridad y el orden en que se abordaran

**Comment by JuanCamiloMartinezLopez** [comment]
Se estudia la propuesta de la fase pasada, resultando la propuesta para la fase actual
![imagen](https://user-images.githubusercontent.com/42418412/125831518-6668059c-fe9b-4454-8140-a0e01579bde7.png)

**Comment by a52290451** [comment]
Por favor adjuntar documento con propuesta de trabajo inicial para el requerimiento:

- Automatización del informe de gestión y certificado de cumplimiento

**Comment by JuanCamiloMartinezLopez** [comment]
Se crea el siguiente [documento](https://docs.google.com/document/d/1B3qRisBNLfFBOS1Bz5uxSfHH2ndB7GcoIWrm7NMaWds/edit?usp=sharing) donde se presenta la propuesta así como las tareas necesarias para desarrollar el requirimiento
