### ISSUE TITLE
modelo de datos para trazabilidad en cumplidos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/cumplidos_cliente#11]
Se requiere guardar la trazabilidad de la aprobación de los cumplidos mensuales, ya que actualmente se remplaza el registro de la persona que realizo la aprobación, por lo tanto no se sabe quien fue la anterior persona en aprobar.

![image](https://user-images.githubusercontent.com/29903400/64967674-90da4c00-d866-11e9-92d4-9dae826d933c.png)

**Comment by jairolh** [comment]
Luego de la revisión del módelo, se recomienda:

- Cambiar el nombre de la tabla "modificacion", para que sea mas acorde con la información que almacena.
- Aplicar lineamientos de modelo de datos, según se definen en el repositorio de introduccion_oas, (con relación a campos de fechas de registro,fecha modificación y estado).
 
- Renombrar campo "tipo_cambio_id", de acuerdo a la información que se almacena.

**Comment by anlramirezs11** [comment]
Además de lo nombrado anterior mente por @jairolh, en la reunión se sugirió: 
* Cambiar el nombre de la tabla "modificacion" por "cambio_estado_pago".
* Cambiar el nombre del campo "tipo_cambio_id" por "estado_pago_mensual_id".
* Agregar comentarios a los campos o tablas que sea necesario.

**Comment by anlramirezs11** [comment]
Modelo modificado teniendo en cuenta lo comentado en la reunión: 
![image](https://user-images.githubusercontent.com/29903400/65236798-f153ce00-da9e-11e9-8001-f7fe4d9c32cc.png)

@jairolh, @corio27 y @blacburn quedo al tanto de cualquier comentario para realizar correcciones.

**Comment by nodier25** [comment]
Faltan el campo fecha creación y campos activo, por favor revisar las tablas

**Comment by BOTOOM** [comment]
según el comentario de @nodier25 se tendría que añadir el campo `activo` para la tabla `cambio_estado_pago`, ya que esa es la nueva tabla propuesta y las otras 2 tablas ya existen en el esquema actual de la base de datos, por ende a esas otras 2 tablas no se les puede agregar los campos ya que generarían problemas o inconsistencias en la estructura de datos

**Comment by anlramirezs11** [comment]
Cambios aplicados: 
![udistrital_core_db](https://user-images.githubusercontent.com/29903400/65520545-59465200-dead-11e9-96e4-f6fe351e1d8b.png)

**Comment by nodier25** [comment]
Buenos días

Sigue faltando los campos de fechas de creación, modificación y activo en algunas tablas, por favor validar. 

Muchas graicas
