### ISSUE TITLE
Apropiación de generalidades del proyecto

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/cumplidos_cliente#110]
Asimilar el funcionamiento general del sistema así, como de su flujo y actividades necesarias por desarrollar en esta nueva fase, de acuerdo a los siguientes indicadores:
 
- [x] Revisión e instalación de repositorios (Crud, Mid y Cliente).
- [x] Revisión de documentación.
- [x] Análisis de requerimientos.

**Criterios de aceptación**

1. Registrar el estado actual en el que se recibe el sistema (Elaboración propia).
2. Registrar inquietudes respecto a los requerimientos analizados.

**Comment by JuanCamiloMartinezLopez** [comment]
Se revisan los repositorios correspondientes al proyecto de cumplidos(Cliente, mid y crud), asi como la documentación dada

**Comment by JuanCamiloMartinezLopez** [comment]
### CUMPLIDOS CLIENTE

Se clona el repositorio, se instalan las dependencias según las indicaciones del **README** y se ejecuta la rama **develop**.
El cliente funciona de la manera esperada,
![imagen](https://user-images.githubusercontent.com/42418412/127066962-8ac5c235-4754-4353-8a89-a4693a69df8e.png)
 sin embargo presenta problemas externos a este, como el siguiente problema en el mid:
![imagen](https://user-images.githubusercontent.com/42418412/127067249-5b37fb69-88c1-4a9e-9502-fb2f7af41acd.png)
así como en sistemas externos a cumplidos:
![imagen](https://user-images.githubusercontent.com/42418412/127067536-010c9308-86cc-4276-a11e-92a8b3a10d13.png)

Se prueba también como se encuentra el cliente desplegado en [pruebas](https://pruebascumplidos.portaloas.udistrital.edu.co/#/) donde presenta los mismos problemas. 
Estas pruebas se hicieron con los usuarios encontrados en la documentación.

**Comment by JuanCamiloMartinezLopez** [comment]
### CUMPLIDOS MID

Se clona el repositorio, se ejecuta conforme a las indicaciones del **README** y se ejecuta en su rama **develop**.
funcionando de la manera esperada.
![imagen](https://user-images.githubusercontent.com/42418412/127068426-df743396-d345-4f64-87b5-56355ac9bbfc.png)
de igual forma se revisa el **swagger** y de igual forma se intenta replicar el [error](https://github.com/udistrital/cumplidos_cliente/issues/110#issuecomment-887073843) mostrado en el cliente.
![imagen](https://user-images.githubusercontent.com/42418412/127069004-cbf04c3a-f458-4734-bf73-b8c4312a27a2.png)
Se cree que este error proviene del servicio de JBPM que se consulta en la función **GetContratosPersona** en el helper **helpers/contratos_contratista.go**

**Comment by JuanCamiloMartinezLopez** [comment]
### CUMPLIDOS CRUD

Se clona el repositorio, se ejecuta conforme a las indicaciones del **README** y se ejecuta en su rama **develop**.
funcionando de la manera esperada.
![imagen](https://user-images.githubusercontent.com/42418412/127070317-a72a40fe-2aca-4d33-89a5-2f9432b4a15a.png)
de igual forma se revisa el **swagger**, se hacen algunas peticiones de prueba.
![imagen](https://user-images.githubusercontent.com/42418412/127070447-576193f7-fb8d-4505-a60d-e07235f7b7dc.png)
![imagen](https://user-images.githubusercontent.com/42418412/127070486-67270958-70c0-4409-a171-ff21123e787f.png)
![imagen](https://user-images.githubusercontent.com/42418412/127070507-cace091b-5dcf-47b0-8c18-ce68fb4c5918.png)
Funcionando como corresponde el crud.

**Comment by JuanCamiloMartinezLopez** [comment]
### CONCLUSIÓN:
Se encuentra que el sistema funciona, con problemas externos a este, también se plantean algunas solicitudes de cara al desarrollo de esta fase:
- Solicitud de usuarios de prueba actualizados con contratos activos o actualización de las bases de datos.
- Solución de problemas con el servicio de JBPM y administrativa_amazon_api.
- Solicitar las variables de entorno del cumplidos_mid. (las pruebas realizadas se hicieron con las variables de entorno de la fase pasada, es posible que el error de JBPM se deba  a una variable desactualizada)

Se pide la revisión al líder técnico @a52290451, así como la colaboración con las solicitudes anteriores.

**Comment by a52290451** [comment]
Se realiza solicitud en Tuleap para la sincronización de la base de datos. A continuación se comparte el Kanban para seguimiento:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=42643

**Comment by a52290451** [comment]
Las variables de entorno actualizadas, relacionadas con MID, se registran en el siguiente kanban:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=40544
