### ISSUE TITLE
Creación de Mock-Ups - Automatización

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/cumplidos_cliente#111]
Se debe realizar la creación de Mock-ups relacionados con "la automatización del informe de gestión y certificado de cumplimiento".

Se debe tener en cuenta:

- Paleta de colores utilizada en Cumplidos.
- Simulación del flujo de trabajo.
- Otros escenarios en los que se pueden o deben ajustar parámetros.

**Criterios de aceptación**

- [x] Registro de Mock-ups (acorde a los formatos/lineamientos de la OAS) a ser presentado en Mesas de Trabajo con clientes/usuarios, cuya firma de aprobación dará inicio al desarrollo.

**Comment by JuanCamiloMartinezLopez** [comment]
Se comienza con la tarea, definiendo mock ups de los posibles interfaces necesarias para el modulo, estos mock ups se encuentran en el siguiente [link](https://app.moqups.com/Nf7XKeHUii/view/page/ad64222d5)

**Comment by JuanCamiloMartinezLopez** [comment]
### PRIMERA VERSION DE LOS MOCK UP
Se crea la primera versión de los mock up para el modulo de automatizacion del informe de gestion y certificado de cumplimiento, esta vistas estan pensadas para el rol de **CONTRATISTA**.
### Vista principal
Siendo asi la vista principal el formulario en el a llenar la informacion necesaria pal informe, esta seria:
- Metas (Asociadas al contrato)
- Nivel de avance ( de la meta)
- Actividades realizadas (Asociadas a la meta)
- Indicador de cumplimiento (respecto a la actividad)
- Soporte (respecto a la actividad)

![imagen](https://user-images.githubusercontent.com/42418412/126015374-8e591844-159d-4079-b998-fc4b2c19c079.png)
Así mismo se podrían crear el mismo numero de metas respecto a las asociadas al objeto contractual, y asociar a esta las actividades que corresponden a la meta.
### Información preliquidacion
Este seria una ventana pop up, accesible desde la vista principal mediante el botón "pre liquidacion". Mostrando este la información correspondiente al pago de este informe y la información bancaria del contratista.
![imagen](https://user-images.githubusercontent.com/42418412/126015723-7995f789-ad44-4b58-9c3b-78bef36df521.png)
### Vista previa del documento
vista preliminar del documento junto a la informacion extraía de los sistemas de la OAS
![imagen](https://user-images.githubusercontent.com/42418412/126015843-7b717a1f-3fba-4b85-befc-c3d47a43537c.png)
### Pop up de confirmación
Ventana para la validación (firma electrónica) del documento.
![imagen](https://user-images.githubusercontent.com/42418412/126015959-8b165e53-8ca9-4140-a37e-b2769e2bef56.png)

para una mejor visualización y probar la interacción entre las vistas puede ingresar el siguiente [link](https://app.moqups.com/Nf7XKeHUii/view/page/a55788bbf)

**Comment by a52290451** [comment]
Se aprueban Mock-Ups y se da inicio al desarrollo del componente.

**Comment by JuanCamiloMartinezLopez** [comment]
### SEGUNDA VERSIÓN DEL MOCK UP

De acuerdo a las reuniones con los interesados y los cambios añadidos al formato, se añaden al mock up de la ventana principal los cambios acordados:
- Espacio para seleccionar el proceso.
- Espacio para ingresar las fechas de inicio y fin que abarcan las actividades realizadas.
- Cambiar el termino "Metas" por "Actividades especificas" y "Soporte" por "Evidencia".
- Campo para ingresar observaciones por actividad realizada

![mock_up_2 drawio](https://user-images.githubusercontent.com/42418412/132966770-ce51e931-b27c-4cda-a8df-28eca2c49502.png)
los mock ups de **informacion de preliquidacion**, **vista previa del documento** y **ventana de confirmación**

**Comment by JuanCamiloMartinezLopez** [comment]
Según las aclaraciones de los interesados en el **SIGUD** se hacen los cambios respectivos al mock up,
También se deja claro que en caso de **otrosi** se debe aclarar el indicativo de este en el titulo-
![mock_up_Automatizacion_informe_gestion drawio](https://user-images.githubusercontent.com/42418412/133310005-f00cc4f2-a6cd-442c-86e3-ec394b092aac.png)

**Comment by a52290451** [comment]
Se validan Mock-ups Presentados en reunión con partes interesadas.
