### ISSUE TITLE
Información necesaria para el proceso de automatización

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#113]
Identificar los datos necesarios para llevar a cabo el registro de información en el informe de gestión y de certificado de cumplimiento.

**Criterios de aceptación**

- [x] Documento en cual se consoliden los datos necesarios y las fuentes para su obtención.

**Comment by JuanCamiloMartinezLopez** [comment]
## INFORMACIÓN NECESARIA PARA EL MODULO DE AUTOMATIZACIÓN DEL INFORME DE GESTIÓN Y CERTIFICADO DE CUMPLIMIENTO

Se recolecta la informacion que el sistema reunirá y agrupara para el funcionamiento del modulo, así como para la generación del pdf resultante.
| Dato | Fuente |
| ------------- | ------------- |
| Dependencia | Administrativa_amazon_api |
| Sede | Administrativa_amazon_api  | 
| Fecha Inicio | Administrativa_amazon_api  |
| Fecha Finalizacion  | Administrativa_amazon_api  |
| CPS  | JBPM  |
| RP  | JBPM  |
| Objeto contratual  | Administrativa_amazon_api  |
| Metas  |necesidades_crud  |
| Tipo cuenta bancaria  | Administrativa_amazon_api | 
| Numero cuenta bancaria  | Administrativa_amazon_api | 
| Entidad Bancaria |  |
| Cargo y dependencia supervisor | Administrativa_amazon_api  |
| Nombre contratista  | Administrativa_amazon_api  |
| Tipo y numero de identificacion | Administrativa_amazon_api |
| Valor a pagar | titan_crud |
| Periodo a pagar  | titan_crud  |
| Valor contrato | Administrativa_amazon_api  | 
| Porcentaje en tiempo ejecutado/restante |  |
| Porcentaje en dinero ejecutado/restante  |   |
