### ISSUE TITLE
Pruebas funcionales y de usabilidad

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#117]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con la automatización del informe de gestión y certificado de cumplimiento, y el módulo de notificaciones.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

**Nota**: utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit?usp=sharing) dispuesto para la aplicación de este tipo de pruebas. En el caso de la Automatización del informe de gestión y certificado de cumplimiento, se deben solicitar a Soporte de primer nivel.

**Comment by a52290451** [comment]
Para el caso de la implementación asociada a notificaciones y gestor documental, las pruebas se realizan por parte del desarrollador, utilizando el formato proporcionado

**Comment by JuanCamiloMartinezLopez** [comment]
### Pruebas funcionales Gestor Documental
[Aplicación pruebas Funcionales y de Usabilidad - Gestor Documental.pdf](https://github.com/udistrital/cumplidos_cliente/files/7851005/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.-.Gestor.Documental.pdf)

### Pruebas funcionales Notificaciones
[Aplicación pruebas Funcionales y de Usabilidad - Notificaciones.pdf](https://github.com/udistrital/cumplidos_cliente/files/7851008/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.-.Notificaciones.pdf)
