### ISSUE TITLE
Propuesta del plan de trabajo para nuevo requerimiento (vista de superusuario)

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#119]
Se requiere propuesta del plan de trabajo relacionada con el nuevo requerimiento descrito a continuación:

- Para el rol de jurídica, se requiere una vista que permita consultar cualquier documento en el sistema así como los anexos que este posea, filtrando por múltiples campos, y poder descargar dichos documentos.

**Criterio de aceptación**

- [x] Documento con propuesta de plan de trabajo en donde se indiquen tareas a realizar y estimación de tiempos.

**Comment by JuanCamiloMartinezLopez** [comment]
## Funcionalidad de visualización de documentos de cumplidos aprobados

Permitir que un usuario de jurídica acceda a los documentos subidos por un contratista cuando esté aprobados para el pago, esto sin depender de la dependencia y de una forma general.

**Propuesta:**
Mostrar al usuario una tabla donde muestra la siguiente información de los aprobados
- **Datos:**

  - Número de contrato
  - Vigencia
  - Año cumplido
  - Mes cumplidos
  - Documento contratista
  - Documentos anexos

Mostrará por defecto todos los registros de aprobación de todas las dependencias, pero se propone crear un filtro de los siguientes datos:

- Número de documento contratista 
- Número de contrato
- Año
- mes
- Vigencia de contrato
- Número de documento Ordenador
