### ISSUE TITLE
Creación de Mock-ups para visualización de documentos de cumplidos aprobados

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#120]
Se requiere el diseño de Mock-ups relacionados con "la visualización de documentos de cumplidos aprobados".

**Se debe tener en cuenta:**

- Paleta de colores utilizada en Cumplidos.
- Simulación del flujo de trabajo.
- Otros escenarios en los que se pueden o deben ajustar parámetros.

**Criterios de aceptación:**

- [x] Registro de Mock-ups (acorde a los formatos/lineamientos de la OAS) a ser presentado en Mesas de Trabajo con clientes/usuarios, cuya firma de aprobación dará inicio al desarrollo.

**Comment by JuanCamiloMartinezLopez** [comment]
## Mock ups

Se crea una primera versión de los mock ups para la visualización de los cumplidos por parte de la oficina de jurídica
- **Vista principal:**
En la vista principal se mostraran una tabla que contendrá la informacion de los cumplidos aprobados, asi como en su ultima columna tendrá un botón para poder ver que documentos están asociados al cumplido, que seran mostrados en la **vista de descarga**.
Así como también tendrá un formulario con el cual se podrán filtrar los cumplidos mostrados en la tabla, este filtro sera presenta por los siguientes datos:
  - Documento contratista (null) Input  text numérico
  - Numero contrato (null) Input text Alfanumérico
  - Vigencia (todas) Select años
  - Año cumplido (todos) Select años
  - mes cumplido (todos) Select meses

   ![Untitled Diagram-Principal(1)](https://user-images.githubusercontent.com/42418412/130145219-c33a22f9-21f7-4e98-b0b2-523641bb8bac.png)
- **Vista de descarga:**
En esta vista se mostraran todos los  documentos asociados a un cumplido y se permitirá descargarlos del gestor documental Nuxeo.
![Untitled Diagram-Descargas(1)](https://user-images.githubusercontent.com/42418412/130145301-b32c8592-0e18-4910-8b46-0561053fef71.png)

**Comment by JuanCamiloMartinezLopez** [comment]
## Mock ups

Se crea una primera versión de los mock ups para la visualización de los cumplidos por parte de la oficina de jurídica
- **Vista principal:**
En la vista principal se mostraran una tabla que contendrá la informacion de los cumplidos aprobados, asi como en su ultima columna tendrá un botón para poder ver que documentos están asociados al cumplido, que seran mostrados en la **vista de descarga**.
Así como también tendrá un formulario con el cual se podrán filtrar los cumplidos mostrados en la tabla, este filtro sera presenta por los siguientes datos:
  - Documento contratista (null) Input  text numérico
  - Numero contrato (null) Input text Alfanumérico
  - Vigencia (todas) Select años
  - Año cumplido (todos) Select años
  - mes cumplido (todos) Select meses

   ![Untitled Diagram-Principal(1)](https://user-images.githubusercontent.com/42418412/130145219-c33a22f9-21f7-4e98-b0b2-523641bb8bac.png)
- **Vista de descarga:**
En esta vista se mostraran todos los  documentos asociados a un cumplido y se permitirá descargarlos del gestor documental Nuxeo.
![Untitled Diagram-Descargas(1)](https://user-images.githubusercontent.com/42418412/130145301-b32c8592-0e18-4910-8b46-0561053fef71.png)
