### ISSUE TITLE
Pruebas funcionales y de usabilidad

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#123]
Se debe realizar la planeación y ejecución de pruebas funcionales y de usabilidad relacionadas con la visualización de documentos de cumplidos aprobados.

**Criterio de aceptación**

- [x] Documento que registre las pruebas funcionales y de usabilidad realizadas.

**Nota:** utilizar el [formato](https://docs.google.com/spreadsheets/d/1oymdKw9XVShKKk71AWzqUjPW-N26OdlRR_IB34X8Acs/edit#gid=481118634) dispuesto para la aplicación de este tipo de pruebas.

**Comment by JuanCamiloMartinezLopez** [comment]
### Pruebas funcionales
Se realizan las pruebas funcionales de la funcionalidad desarrollada, y se registran según el formato definido en el siguiente [link](https://docs.google.com/spreadsheets/d/1LklgefYndtNNYJC6HUcGIK84PcQ7NMfUrD2GOmIxzAk/edit?usp=sharing)
