### ISSUE TITLE
Despliegue en preproducción

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#125]
Realizar la gestión necesaria para desplegar la nueva funcionalidad en ambiente de pruebas.

**Criterios de aceptación**

- [x] Pull request en release para las APIs ajustadas y el cliente.

**Comment by a52290451** [comment]
Se solicita la creación de un botón que permita realizar limpieza de filtros.

**Comment by JuanCamiloMartinezLopez** [comment]
### Botón para limpiar filtros
Se añade un botón "limpiar" que permite que habilita una vez realizado alguna selección o ingreso de texto al formulario de búsqueda.
![imagen](https://user-images.githubusercontent.com/42418412/131719834-29d07b6d-99dc-4456-a194-0858d9b01a74.png)
Este botón, limpiara todos los campos del formulario de búsqueda y reinicia la tabla de cumplidos, mostrando los últimos 50 cumplidos aprobados.
