### ISSUE TITLE
Diseño de APIs para envío y recepción de notificaciones.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#144]
Presentar diseño asociado al envío y recepción de notificaciones al interior de los sistemas y mediante correo electrónico.

**Criterio de aceptación**

- [x] Diseño del modulo de notificaciones.

**Comment by FelipeVel** [comment]
Se desarrollan funciones de prueba en local que permiten publicar y escuchar notificaciones del servicio implementado.
