### ISSUE TITLE
Diseño para configuración de servicios en AWS.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#145]
Realizar el diseño asociado a la configuración necesaria en servicios de AWS para el módulo de notificaciones.

**Criterios de aceptación**

- [x] Diseño asociado a configuración en servicios de AWS necesarios.

**Comment by FelipeVel** [comment]
Se configura en usuario local el servicio SNS para hacer pruebas sobre las funciones desarrolladas.
