### ISSUE TITLE
Despliegue en ambiente de producción

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#155]
Se debe realizar el despliegue en ambiente de producción, teniendo en cuenta la serie de lineamientos y pasos a seguir, previamente definidos.

**Criterios de aceptación**

- [x] Check-list actualizado para salida a producción.
- [x] Pull Request en rama Master con cambios realizados.

**Comment by JuanCamiloMartinezLopez** [comment]
Se sube el [checklist ](https://docs.google.com/document/d/1YvTCgQYu2KLopo0rmLpZW0wjslwEcPCC/edit?usp=sharing&ouid=102281073206082450559&rtpof=true&sd=true
)con el formato definido para aplicativos existentes a produccion.
