### ISSUE TITLE
Análisis y Diseño - Módulo para Parametrización de fechas de apertura y cierre.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#160]
Se requiere llevar a cabo el análisis y diseño relacionado con el módulo de parametrización de fechas de apertura y cierre para carga y validación de dócumentos en Cumplidos.

**Criterios de aceptación**

- [x] Ánalisis de las necesidades asociadas para desarrollar el módulo.
- [x] Mock-ups.
- [ ] Propuesta de actualización de modelo de datos.

**Comment by JuanCamiloMartinezLopez** [comment]
#  Análisis de las necesidades asociadas para desarrollar el módulo.

Se hace una propuesta inicial en la cual la persona con rol de **SUPERVISOR** pueda parametrizar las fechas de carga de los cumplidos a los cuales esta asociado como supervisor, esto por mes y año, donde podrá escoger entre tres tipos de fechas de carga de documento:
- **Sin Limite:**
Sera la opción por defecto.
- **Periodo para un mes en particular:**
Opción donde al mes de un año en particular se le podrá asignar una periodo para subir los cumplidos.
- **Periodo para todos los meses:**
Opción para definir un periodo que será el por defecto de todos los meses.

**Comment by JuanCamiloMartinezLopez** [comment]
# Mock ups
Se proponen los siguientes mock ups para la interfaz de la funcionalidad de parametrización de fechas en la carga de cumplidos.
- **Principal:**
Vista principal para seleccionar los años y meses a parametrizar, mediante estos drop list también se podrá escoger la opción de "todos" para años y meses.
![mock_up-Principal drawio](https://user-images.githubusercontent.com/42418412/150371875-763c46a0-6802-4760-952e-1e0bf1c739c8.png)
- **Periodo parametrizable:**
Vista que permitirá parametrizar un periodo entre dos fechas para la carga del cumplido, este podra general o especifico para un mes y año 
![mock_up-Periodo drawio](https://user-images.githubusercontent.com/42418412/150372581-561b2206-f836-4ec4-9dd8-17303e3a481b.png)

- **Sin limite:**
Estado por defecto donde no se contempla fecha para la carga de los documentos.
![mock_up-Sin limite drawio](https://user-images.githubusercontent.com/42418412/150372611-3b39b095-be8d-4f82-b967-4555eddbb57b.png)

**Comment by JuanCamiloMartinezLopez** [comment]
# Modelo de datos

Se propone el siguiente modelo para la parametrización de fechas
![parametrizacion_fechas_modelo_db](https://user-images.githubusercontent.com/42418412/150373162-f426e7c5-33a5-4d1c-a166-22250611e000.png)
las fechas serán asociadas al documento del supervisor, de igual forma se tiene el cuenta el mes y año de esta, teniendo en cuenta que el mes y año "null" hará referencia a todos, de igual forma el valor "null" en las fechas de inicio y fin representara el no tener limite.

**Comment by a52290451** [comment]
Buen día,

Queda pendiente validación del modelo de datos por parte de Arquitectura y de los DBAs
