### ISSUE TITLE
Despliegue en test de cliente de cumplidos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/cumplidos_cliente#17]

**Comment by anlramirezs11** [comment]
30/09/2019
- Se agrega el menú para test.
- Se cambia el endpoint de Finaanciera_mid para que sirva conautenticación. 
- Se editar el api administrativa_crud para agregar el swagger de la nueva tabla. 
- Escribirle a Jhon para habilitar los endpoints en wso2

**Comment by anlramirezs11** [comment]
1/10/2019
* Se verifica el Api administrativa_crud para confirmar que esté funcionando correctamente, pero al hacerle peticiones para la nueva tabla agregada devuelve el siguiente mensaje: 

![image](https://user-images.githubusercontent.com/29903400/65995704-a8ffbd00-e45b-11e9-891e-9c8b7dc686fb.png)


*
*
*

**Comment by BOTOOM** [comment]
el endpoint https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_mid_api/v1/aprobacion_pago/solicitudes_supervisor_contratistas/19483708

responde en null por lo tanto se ha de proceder lo mas pronto posible a realizarle refactor ya que ese null lo debe de responder en json

**Comment by BOTOOM** [comment]
https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_mid_api/v1/aprobacion_pago/solicitudes_ordenador_contratistas/19483708?limit=10&offset=0

este también responde un null

**Comment by BOTOOM** [comment]
el martes 15 de octubre se realizare en compañía del dba una actualización de algunas registros con los cuales se espera que se pueda proceder con las pruebas y varios ajustes en cumplidos, cabe aclarar que aun no esta arriba el api de nuxeo para la aprobación de documentos por ende esto aun es una demora para el proyecto.

**Comment by BOTOOM** [comment]
en el presente issue dejare notas de los procesos que debo de tener en cuenta para la adicion de los cambios a cumpldios

**Comment by BOTOOM** [comment]
al adicional un documento como contratista, justo despues del post a core, se añadira el post al flujo de nuxeo.


cuando el contratista elimina un doc8mento cargado, este registro no se elimina de core, ni se elimina de nuxeo, por ende alli se tiene que dispara la cancelacion del flujo

**Comment by BOTOOM** [comment]
ver donde se hace el ver documentos de un contratista desde un supervisor, u ordenador, alli capturar el string de contenido y usar el id del documento.
parece que parte de eso ya se hace, algo similar, ver y reutilizar a conveniencia.

verificar el rechazar documentos ya que su mensaje cuand se rechaza no es el correcto

**Comment by BOTOOM** [comment]
la carga de los documentos en el cliente, se mantiende en objetos por aparte, permitiendo ciclos for.

**Comment by BOTOOM** [comment]
revisar también el mensaje de error cando se prueba, funciona el aprobar y rechazar, pero manda mensaje de error

**Comment by BOTOOM** [comment]
temas similares a los mencionados para el ordenador de gasto

**Comment by BOTOOM** [comment]
el documento solo se publica cuando el proveedor aprueba, si el proveedor rechaza no pasa nada con el documento.

el flujo se crea cuando el contratista sube archivos y el flujo se cancela cuando el contratista elimina los archivos

**Comment by BOTOOM** [comment]
para la trazabilidad, esta sucede cuando el ordenador apreuba o el supervisor, adicionalmente se debe de disparar allí mismo la peticion de la trazabilidad.


este mismo proceso al rechazar.

**Comment by BOTOOM** [comment]
ya se logra disparar el flujo y detenerlo desde el cliente

**Comment by BOTOOM** [comment]
ya se logra aprobar desde la vista de supervisor, la aprobación se puede de manera masiva, falta realizar alguna correcciones en la vista

**Comment by BOTOOM** [comment]
se realiza la adición de métodos para la traza con el ordenador, parte de esto toco haciendo algunos cambios en el mid de administrativa, se espera a que se le concedan permisos a la api que guarda la trazabilidad, para posteriormente hacer pruebas sobre ello.
