### ISSUE TITLE
Creación de RFC - Novedades Otro Si en Cumplidos

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#226]
Se requiere realizar la creación del RFC asociado a la modificación del modelo de datos de Cumplidos (sistema en uso) y tareas posteriores de Novedades de tipo Otro Si.

Se debe tener en cuenta los siguientes campos a completar:

- Solicitud técnica de porqué se requiere.
- Evaluación tecnica (impacto del cambio) - sistemas y bases de datos que se alteran.
- Necesidad, justificación.
- Efectos de no implementar dichos cambios.
- Plan de reversión.
- Identificar y describir de manera detallada los cambios.

**Comment by JuanCamiloMartinezLopez** [comment]
### Evaluación técnica
Se requiere agregar a la base de datos: udistrital_administrativa, esquema: cumplidos, tabla: pago_mensual , las siguientes columnas:
| Name        | Data type | length/Precision |
|--------------|:-----:|-----------:|
| numero_cdp | character varying |        20 |
| vigencia_cdp      |  numeric |          4,0 |


lo cual también requiere el cambio en las apis cumplidos_crud y cumplidos_mid, para ajustar el modelo de pago_mensual. De igual forma ajustar los scripts sql de la migración con el nuevo cambio en cumplidos_crud.

**Comment by JuanCamiloMartinezLopez** [comment]
### Nuevo modelo de base de datos
Se agrega el modelo con el cambio:
![nuevo_modelo_cumplidos_db](https://user-images.githubusercontent.com/42418412/167173461-bb71e03a-eb4b-4e72-b640-17aa5b4ea8a1.png)
Así como el editable de este:
[nuevo_modelo_cumplidos_db.zip](https://github.com/udistrital/cumplidos_cliente/files/8642161/nuevo_modelo_cumplidos_db.zip)
También se anexa el script necesario para la modificación:

``` sql
ALTER TABLE cumplidos.pago_mensual 
ADD COLUMN numero_cdp character varying(20),
ADD COLUMN vigencia_cdp numeric(4,0);
```

**Comment by milo19980525** [comment]
Caso Tuleap asociado a RFC:

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=46947

**Comment by milo19980525** [comment]
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=49993
