### ISSUE TITLE
Corrección de Bug Visual - Tabla de cumplidos

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#237]
Se requiere realizar la corrección de bug visual asociado a la tabla de cumplidos por contrato en la cual no se visualizan los nombres de los campos debido al tamaño de la tabla en general.

**Comment by JuanCamiloMartinezLopez** [comment]
### Bug tabla soportes de un contrato
En la tabla donde mostramos los soportes asociados a un contrato se presenta un error al mostrar el label en la cabecera de las columnas y los datos, así como se ve a continuación:
![error_1](https://user-images.githubusercontent.com/42418412/176349102-f605f6d2-4c23-4534-9161-b2c91bbd6897.PNG)
Esto es debido a que se carga en un modal, donde se chocan algunas propiedades como el indice-z y el tamaño disponible.

esto se soluciono eliminando el modal, y alternando entre tablas con un ng-if, y agregando un botón para retornar a la tabla de contratos, quedando de la siguiente:
![solucion](https://user-images.githubusercontent.com/42418412/176351505-8f044e99-b3c1-4d88-bddd-c16fc7037f9b.PNG)
