### ISSUE TITLE
Creación de RFC para permitir asociar un informe de gestión a un cumplido especifico

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#238]
Se requiere realizar la creación del RFC asociado a la modificación del modelo de datos de Cumplidos (sistema en uso) y tareas posteriores para lograr asociar un informe de gestión con su respectivo pago mensual, en la tarea por conseguir crear mas de un cumplido por mes.

Se debe tener en cuenta los siguientes campos a completar:

- Solicitud técnica de porqué se requiere.
- Evaluación tecnica (impacto del cambio) - sistemas y bases de datos que se alteran.
- Necesidad y justificación.
- Efectos de no implementar dichos cambios.
- Plan de reversión.
- Identificar y describir de manera detallada los cambios.

**Criterios de aceptación**

- [x] Link de kanban con solicitud de RFC
- [x] Material de soporte para RFC (scripts y commits)

**Comment by JuanCamiloMartinezLopez** [comment]
### Cambio en la tabla informe
se agrega una columna en el informe para hacer referencia al pago_mensual como se muestra en el nuevo modelo.
![informe_modelo_db](https://user-images.githubusercontent.com/42418412/177837385-c95bfeb0-db3b-440d-bb51-0d4f441a1e06.png)
de igual forma se crea el script para realizar este cambio:
```sql
ALTER TABLE informe_gestion.informe ADD COLUMN pago_mensual_id INT NOT NULL
CONSTRAINT fk_informe_pago_mensual REFERENCES cumplidos.pago_mensual (id)
ON DELETE NO ACTION ON UPDATE NO ACTION;
```

**Comment by JuanCamiloMartinezLopez** [comment]
### Propuesta eliminación de columnas redundantes
Con la relación propuesta anteriormente entre cumplidos.pago_mensual e informe_gestion.informe se presentaría redundancia de datos, específicamente en:
| cumplidos.pago_mensua    | informe_gestion.informe |
| ----------- | ----------- |
| numero_contrato     | contrato       |
| vigencia_contrato   | vigencia        |
| mes     | mes       |
| ano   | anio        |
| documento_persona_id   | documento_contratista        |

por esto se propone eliminar estas columnas de la tabla informe_gestion.informe
```sql
ALTER TABLE informe_gestion.informe
DROP COLUMN contrato,
DROP COLUMN vigencia,
DROP COLUMN mes,
DROP COLUMN anio,
DROP COLUMN documento_contratista;
```

**Comment by JuanCamiloMartinezLopez** [comment]
### Nuevo modelo informe gestion

![informe_modelo_db (1)](https://user-images.githubusercontent.com/42418412/178037712-ad74d3b3-cd5f-4b4a-86e2-9f54fe89717c.png)

**Comment by a52290451** [comment]
Se presenta creación de RFC: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=47802

**Comment by JuanCamiloMartinezLopez** [comment]
### Error creación constraint
al momento de crear el constraint de llave foránea en informe referenciado a la llave primaria de la tabla cumplidos.pago_mensual nos da este error:
![image](https://user-images.githubusercontent.com/42418412/178407962-f06bf113-3add-4ee7-a7ee-7019ab4a59a4.png)
por esto se debe a la falta de un constraint de llave primaria en la tabla pago_mensual, por eso se pasa a su creacion
```sql
ALTER TABLE cumplidos.pago_mensual ADD CONSTRAINT pk_pago_mensual PRIMARY KEY (id);
```

**Comment by milo19980525** [comment]
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=49993
