### ISSUE TITLE
Pruebas funcionales - Casos de Novedades y Multiples cumplidos para un mismo mes.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#239]
Se requiere implementar pruebas funcionales asociadas a la lógica de novedades implementada en API Mid, verificando los múltiples casos de novedad que puede presentar un contrato (doble cesión, casos múltiples de otro si, suspensiones...) se deben registrar los casos probados en un documento excel. 

Tambien se requiere  implementar pruebas para múltiples cumplidos en un mismo mes dependiendo de las novedades que presente un contrato determinado. En esta caso se requiere que las novedades estén asociadas en TITAN para realizar el calculo de preliquidación del contrato de acuerdo a esas novedades. Existen dos caminos posibles:
1. Se preliquide de forma manual con los jobs necesarios.
3. Se realice la preliquidación de forma automática con la información proveniente desde Novedades.

**Criterio de aceptación**

- [ ] Pruebas funcionales asociadas a casos de novedades.
- [ ] Pruebas funcionales asociadas a casos de multiples cumplidos en un mismo mes.

**Comment by JuanCamiloMartinezLopez** [comment]
### Novedades
Se realizan pruebas de las novedades de cara al registro de los contratos
- Otro si
En caso de novedad de otro si, los otro si aparecerán como otro contratos donde  cambia la informacion del CDP asi como las fechas de inicio y fin.
```json
        {
            "NumeroContratoSuscrito": "1112",
            "Vigencia": "2022",
            "NumeroCdp": "2175",
            "VigenciaCdp": "2022",
            "NumeroRp": "6185",
            "VigenciaRp": "2022",
            "NombreDependencia": "DOCTORADO EN INGENIERIA",
            "NumDocumentoSupervisor": "79950025",
            "FechaInicio": "2022-10-11T00:00:00Z",
            "FechaFin": "2023-04-13T00:00:00Z"
        },
        {
            "NumeroContratoSuscrito": "1112",
            "Vigencia": "2022",
            "NumeroCdp": "2172",
            "VigenciaCdp": "2022",
            "NumeroRp": "6481",
            "VigenciaRp": "2022",
            "NombreDependencia": "DOCTORADO EN INGENIERIA",
            "NumDocumentoSupervisor": "79950025",
            "FechaInicio": "2023-03-13T00:00:00Z",
            "FechaFin": "2023-05-13T00:00:00Z"
        }
```

**Comment by JuanCamiloMartinezLopez** [comment]
### Pruebas de la mesa de trabajo del 28/10/2022
De las pruebas realizadas de los casos de novedades de cesión y otro si, se registran los resultados en el siguiente formato:
[Aplicación pruebas Funcionales y de Usabilidad Cumplidos.xlsx](https://github.com/udistrital/cumplidos_cliente/files/9905949/Aplicacion.pruebas.Funcionales.y.de.Usabilidad.Cumplidos.xlsx)
