### ISSUE TITLE
Despliegue en producción - (Novedades y multiples cumplidos para un mismo mes)

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#240]
Se requiere listar los elementos necesarios para salir a producción con las APIs del sistema y el cliente, así como registrar la trazabilidad de las solicitudes que se realicen.

- Se despliega en producción el desarrollo asociado a la parte final de novedades en cumplidos y la capacidad del sistema para permitir generar mas de un cumplido por mes, de acuerdo al tipo de novedad que se presente.

**Criterios de aceptación**

- [x] Checklist de salida a producción por cada API y el cliente.
- [x] Trazabilidad de peticiones y commits para salida a producción.
- [x] Estabilización del sistema en producción.

**Comment by JuanCamiloMartinezLopez** [comment]
### Checklist salida a producción
Se adjuntan los checklist de la salida a producción del día 4 de Noviembre:
 
- [Checklist Cumplidos Cliente.docx](https://github.com/udistrital/cumplidos_cliente/files/9965458/Checklist.Cumplidos.Cliente.docx)
- [Checklist Cumplidos Crud.docx](https://github.com/udistrital/cumplidos_cliente/files/9965459/Checklist.Cumplidos.Crud.docx)
- [Checklist Cumplidos Mid.docx](https://github.com/udistrital/cumplidos_cliente/files/9965460/Checklist.Cumplidos.Mid.docx)
