### ISSUE TITLE
Definir tablas necesarias para crear contratos ficticios

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#243]
- [x] Diagnosticar que tablas interfieren en el proceso de creación de un contrato.

- [x] Determinar las columnas obligatorias en las que debe existir información del contrato.

**Comment by JuanCamiloMartinezLopez** [comment]
### Tablas para la creación de contratos de prueba

Base de datos: Udistrital
Esquema: Argo

- contrato_general
- contrato_suscrito
- acta_inicio
- contrato_disponibilidad
- novedad_postcontractual
