### ISSUE TITLE
Apropiación de generalidades técnicas- CUMPLIDOS

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#246]
Tarea asociada a la adopción del sistema de Cumplidos Contratistas.

Observaciones:
1. Se deben instalar los repositorios de cumplidos_crud, cumplidos_mid y cumplidos_cliente desde la rama MASTER.
2. Se requieren configurar las variables de entorno de cada uno de los repositorios.
3. Se deben probar por separado los repositorios clonados.
4. Se deben conectar entre si los 3 repositorios.
5. Se deben realizar pruebas de funcionamiento entre los servicios que comparten los repositorios.

**Criterios de aceptación**

- [x] Trazabilidad de tareas realizadas.

**Comment by a52290451** [comment]
Se adjunta link de sesiones de inducción:

Sesión 1: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/blsierraf_udistrital_edu_co/Efu-0dtQiENDov9MdFjbgVkB8rF1YccovPH6DjNCJxEYJA?e=8fxiZI
Sesión 2: https://udistritaleduco-my.sharepoint.com/:v:/g/personal/blsierraf_udistrital_edu_co/EWeWHeZHPpBMtQPx5t5Tq0kBrSJJQrtLhS6ZIvk0suX-ag?e=FBUBAT

**Comment by Mechaz123** [comment]
Se ha realizado la instalación de los diferentes elementos necesarios:
- Golang
- Beego y bee
- Postgresql
- pgadmin3

**Comment by Mechaz123** [comment]
Se pone en funcionamiento CUMPLIDOS_Cliente, de manera local

![Cliente](https://user-images.githubusercontent.com/73924638/198766162-235c9cd0-4f57-46e7-aee1-c03645458074.PNG)

**Comment by Mechaz123** [comment]
Se pone en funcionamiento CUMPLIDOS_Crud, de manera local

![image](https://user-images.githubusercontent.com/73924638/198894617-0251f694-791b-476f-a392-6ec7b5b51bde.png)

**Comment by Mechaz123** [comment]
Se pone en funcionamiento CUMPLIDOS_Mid, de manera local
![image](https://user-images.githubusercontent.com/73924638/198907885-6d407a72-a8ee-4353-a8ef-1dd1f05b313a.png)

**Comment by a52290451** [comment]
Se da por terminada fase de apropiación de generalidades técnicas
