### ISSUE TITLE
Apropiación de generalidades - Documentación y Manuales de usuario.

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#249]
Tarea asociada a la adopción del sistema de Cumplidos Contratistas:

1. Se debe revisar documentación asociada a Cumplidos Contratistas, con el objetivo de conocer sus funcionalidades, flujos de trabajo, roles, componentes, tecnologías y demas elementos relacionados.
2. Se requiere repasar los manuales de usuario disponibles para comprender el alcance y las funcionalidades que posee cada rol dentro del sistema.

**Criterios de aceptación**

- [x] Trazabilidad de tareas realizadas.
- [x] Preguntas acerca de las particularidades del sistema.

Links de apoyo:
1. [Documentación](https://drive.google.com/drive/folders/1ET4Smux3dbH9JcmHfV5LoqZweN3urSiy?usp=sharing)
2. [Manuales de usuario](https://docs.google.com/spreadsheets/d/1q94p70_t46GpJ2eKVlBDFGRDWFxKCGMMclIWWCT-kjc/edit?usp=sharing)

**Comment by Mechaz123** [comment]
En base a la lectura de los documentos, generé el siguiente esquema, tratando de resaltar los puntos más importantes y dudas:

1. LÓGICA DE NEGOCIO

    - Contrato por prestación de servicios y vinculación especial
    - Supervisor de CPS es registrado por la OAS y para VE es el coordinador del proyecto curricular
    - Formato de certificado de cumplimiento e informe de gestión

3. ACTORES

    *Para CPS
        - Contratista: Persona que interactua con el sistema o mejor llamado Docente
        - Supervisor: Aprueba o desaprueba las solicitudes de los contratistas
        - Ordenador del gasto: aprueba o desaprueba $$$$$$$
      
     *Para DVE
        - Docente: Se comporta como contratista
        - Coordinador del proyecto curricular: actúa como supervisor
        - Decano de Facultad: Aprueba o desaprueba $$$$$$$

4. DUDAS
    - ¿Que es Titan?
    - ¿Que es Agora?

**Comment by a52290451** [comment]
Se solucionan dudas he inquietudes a través de una reunión: 

[Planeación de actividades - Cumplidos DVE](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/blsierraf_udistrital_edu_co/EdyPR-qMxrhJqAymWiOeKCkBa80fDTatFPKulC47OhDlVg?e=q4s79V)
