### ISSUE TITLE
Corrección de hallazgos encontrados

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#252]
Corrección de los hallazgos encontrados en la reunión con soporte de segundo nivel.

- [x] Delimitación de fechas de cargue de informe de gestión (caso de 10 meses con un solo día en el último mes).
- [x] Parametrización de visualización de contratos según novedades (caso otro si)
- [x] Parametrización de visualización de contratos según novedades (caso cesión)
- [x] Parametrización de visualización de contratos según novedades (suspensión)
- [x] Parametrización de visualización de contratos según novedades (terminación anticipada)

**Comment by JuanCamiloMartinezLopez** [comment]
### Resultado de pruebas
Se deja constancia de los casos y sus resultados en el siguiente documento:
[Plan de Pruebas Piloto - Cumplidos.docx](https://github.com/udistrital/cumplidos_cliente/files/9938417/Plan.de.Pruebas.Piloto.-.Novedades.-.ARGO.docx)

**Comment by milo19980525** [comment]
[Pna de pruebas piloto cumplidos](https://docs.google.com/document/d/1u-4PPT_L1Esf5kNzooG7UPOihZHwS5Ad/edit?usp=share_link&ouid=100698401433907561666&rtpof=true&sd=true)
