### ISSUE TITLE
Apropiación de generalidades técnicas y de documentación - Cumplidos DVE

### ISSUE THREAD

**Issue by a52290451** [udistrital/cumplidos_cliente#254]
Tareas asociadas a la adopción del sistema de Cumplidos DVE:

1. Se debe revisar documentación asociada a Cumplidos DVE, con el objetivo de conocer sus funcionalidades, flujos de trabajo, roles, componentes, tecnologías y demas elementos relacionados, de acuerdo con el material de apoyo existente.
2. Se requiere repasar los manuales de usuario disponibles para comprender el alcance y las funcionalidades que posee cada rol dentro del sistema.
3. Se debe estudiar técnicamente el módulo, mediante los repositorios de administrativa_crud, administrativa_mid y administrativa_cliente.
4. Se rquiere comprobar acceso a la base de datos udistrital_core_db, esquema administrativa. Realizar pruebas a través de consultas.
5. Repasar modelo de datos de cumplidos DVE y realizar consultas a través de la BD.

**Criterios de aceptación**

- [x] Trazabilidad de tareas realizadas.
- [x] Preguntas acerca de las particularidades del sistema.
- [x] Cumplimiento de los puntos señalados.

**Material de apoyo de apoyo**

1. [Grabación de aspectos técnicos](https://drive.google.com/file/d/1g003nT92iQmjOJsphuiW8j5jBNyeEud3/view?usp=share_link) - Revisar a partír del minuto 70.
2. [Manual de usuario.](https://ti.udistrital.edu.co/sites/default/files/documentacion/2021-01/INS%20Solicitud%20Cumplidos%20-%20Docentes.pdf)
3. [administrativa_mid](https://github.com/udistrital/administrativa_mid_api), [administrativa_crud](https://github.com/udistrital/administrativa_crud_api), [administrativa_cliente](https://github.com/udistrital/administrativa_cliente)
4. 
![image (1)](https://user-images.githubusercontent.com/36229498/199541688-0dbb5e25-9a95-4244-8a41-8b2a829d8b18.png)

**Nota:** Para probar el aplicativo, se requiere solicitar usuarios de prueba.

**Comment by Mechaz123** [comment]
Se realiza la lectura del manual de usuario asociado a cumplidos DVE

![image](https://user-images.githubusercontent.com/73924638/199760704-9fbb3ed7-52a7-4e81-907f-f7822c1a33d7.png)

**Comment by Mechaz123** [comment]
Se realiza la revisión de administrativa_crud_api
![image](https://user-images.githubusercontent.com/73924638/200077746-b0956956-7adf-4065-b8e2-ee39c6d071f6.png)

**Comment by Mechaz123** [comment]
- Se realiza la conexión a la base de datos udistrital_core_db
![image](https://user-images.githubusercontent.com/73924638/200080297-8a22de09-f602-4090-91e3-894897692ced.png)

**Comment by a52290451** [comment]
Solución de dudas:

1. El cliente puede realizar llamados directamente al CRUD, sin necesidad de pasar por el MID, en los casos en que no se necesite procesar lógica. Es decir, cuando requiera información concreta de las bases de datos, expuesta a través de uno de los servicios del CRUD.
