### ISSUE TITLE
Pruebas funcionales

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#291]
Realizar pruebas funcionales asociadas a la optimización realizada, dónde se debe tener en cuenta cada una de las funcionalidades afectadas por este hito.

1. Pruebas de funcionamiento en la consulta de contratos con novedades en la de selección de cargue de informe.
2. Pruebas de funcionamiento en el cargue de documentos
3. Prueba de funcionamiento al guardado y actualización del informe de gestión.
4. Prueba de funcionamiento al consultar los ordenadores y supervisores, información de preliquidación, documentos, entre otros.
5. Prueba de funcionamiento de aprobación de informe.

**Criterio de aceptación**

- [x]  Pruebas funcionales asociadas a funcionalidades afectadas por la optimización.
- [x]  Formato de hallazgos con las pruebas realizadas.

**Comment by a52290451** [comment]
Se validan y aprueban pruebas funcionales realizadas
