### ISSUE TITLE
Despliegue de optimizaciones a producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#293]
De acuerdo con las optimizaciones realizadas, señaladas en #291 y #319 , se requiere realizar la salida a producción, teniendo en cuenta los siguientes requerimientos:

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [x] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2
- [x] Revisión y actualización de variables de entorno
- [x] Pruebas funcionales (grupo de soporte)
- [x] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [x] Pruebas de usuario (Preguntar Revisión SIGUD)
- [x] Pruebas unitarias (equipo de desarrollo)
- [x] Revisión de sincronización de bases de datos en ambientes (prueba y producción)
- [x] Revisión de estado de bases de datos (ETL)
- [x] Revisión de actualización de APIs consumidas (terceros, transversales)
- [x] Definición y/o actualización de manual de usuario/videotutoriales
- [x] Documento técnico

**Comment by milo19980525** [comment]
Ejemplo de documento técnico: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EUOmAF6tQedIvmDIAiZEZdABJANRDhU7via-a64CljTcnQ?e=kWgAXX

**Comment by JuanCamiloMartinezLopez** [comment]
### Documento técnico cumplidos CPS
Documento con las especificaciones tecnicas del sistema cumplidos CPS
[Descripcion tecnica CUMPLIDOS.docx](https://github.com/udistrital/cumplidos_cliente/files/11665834/Descripcion.tecnica.CUMPLIDOS.docx)

**Comment by JuanCamiloMartinezLopez** [comment]
### Despliegue 
Se realiza el despliegue de forma exitosa.
