### ISSUE TITLE
Diagnóstico de cumplidos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#297]
Teniendo en cuenta la finalización de la contratación realizar un documento dónde se evidencie:

- [x] El estado actual del sistema
- [x] Bugs, errores conocidos y deuda técnica
- [x] Limitaciones
- [x] Actividades realizadas para salir a producción – Equipo de desarrollo
- [x] Actividades requeridas para salir a producción – Equipo de desarrollo
- [x] Actividades requeridas para salir a producción – Terceros
- [x] Usuarios de prueba – WSO2
- [x] Videotutoriales y Manuales de usuario
- [x] Plan de mejoramiento

**Comment by JuanCamiloMartinezLopez** [comment]
### Diagnóstico Cumplidos Marzo 2023 

Se crea el documento con los puntos solicitados
[Diagnostico Cumplidos.docx](https://github.com/udistrital/cumplidos_cliente/files/10963447/Diagnostico.Cumplidos.docx)
