### ISSUE TITLE
Inyección de metadatos a los documentos de nuxeo

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/cumplidos_cliente#3]
Con fines de implementar un filtro de búsqueda basado e metadatos , el cual se describirá en un issue futuro.

Se requiere poder realizar la inyección de metadatos a documentos en nuxeo. estos metadatos deben ser inyectados a los documentos subidos.

Según se ha entendido. el proceso es el siguiente:
- subir un documento.
- con la identificación del documento en nuxeo se inyectan metadatos.

con eso en mente se tiene en cuenta que los metadatos se ingresan después de que el documento ha sido cargado.

pasos recomendados a seguir.
 

- [x] leer documentación sobre nuxeo y metadatos en este.

- [x] leer foros , ejemplos, etc...donde se desarrollen temáticas similares en nuxeo.

- [x] realizar pruebas sobre nuxeo con el fin de inyectar metadatos.

- [x] con el fin de comprobar si se han inyectado metadatos, se sugiere hacer consulta para obtener los metadatos de un documento allí cargado.

- [ ] documentar el proceso , con sus avances, con el fin de que este pueda ser leído por otros miembros de la oficina para tener en cuenta la curva de aprendizaje de esta temática.

- [x] realizar pruebas exitosas de inyección de metadatos y documentarlas.

- [x] comprobar estas pruebas con las obtención de los metadatos (lo cual funcionara como adelanto para el filtro)

**Comment by anlramirezs11** [comment]
Algunos enlaces que pueden servir en la investigación de como insertar metadatos: 
* https://answers.nuxeo.com/general/q/4e9b528e5f8c4a52bd1ddf7e753507ce/Inserting-metadata-to-document

**Comment by anlramirezs11** [comment]
13/08/2019

Se solicita el token para el cliente de cumplidos. Se realizan cambios en la configuración local del cliente para que sirvan las apis a las que se conecta. y se piden las credenciales para ingresar a nuxeo: https://documental.udistrital.edu.co/nuxeo/

**Comment by anlramirezs11** [comment]
14/08/2019
Se intenta conectar a nuxeo desde postman pero no se logra. 
Se explora la herramienta de Nuxeo Platform.

**Comment by anlramirezs11** [comment]
15/08/2019
* https://doc.nuxeo.com/assets/main/archived-documentation/Nuxeo_Platform_5.6_UserGuide-ES.pdf
* https://doc.nuxeo.com/nxdoc/document-json-extended-fields/
* https://stackoverflow.com/questions/48704196/how-to-make-a-query-with-properties-parameter-in-nuxeo
*

**Comment by anlramirezs11** [comment]
16/08/2019

* Se define que Core (Fabio) va a relizar un servicio de conexión con nuxeo.
* Se debe comparar la plantilla de nuxeo con los metadatos que solicita la universidad para poder relacionar los datos que se puedan.

![image](https://user-images.githubusercontent.com/29903400/63180298-99dfbf80-c013-11e9-81e2-10988e9497ff.png)
