### ISSUE TITLE
Servicio que consulta documentos y data de solicitudes de pago

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#308]
Realizar servicio que consulte los datos asociados a la solicitud de pago descritos en la issue #307.

**Criterios de aceptación**

- [x] Desarrollo en local.
- [x] Push a feature /revision_reversion
- [x] Pruebas locales
- [x] PR a dev

**Comment by JuanCamiloMartinezLopez** [comment]
### Servicio de documentos asociados a un pago mensual

Se muestra la funcionalidad en pruebas:
![image](https://user-images.githubusercontent.com/42418412/236914887-5e332a33-642a-4a72-b3b9-416bb9fb3404.png)
