### ISSUE TITLE
Creación ETL para actualizar solicitudes al cambio ordenador/supervisor

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#318]
Se debe crear un ETL que permita actualizar las solicitudes de cumplidos que no han sido pagadas cuando haya un cambio de ordenador/supervisor.

**Especificaciones técnicas**

- El último desarrollo asociado se encuentra cargado en el repositorio en la rama develop, tanto para el cliente como para el API mid.

**Sub Tareas**

- [x] Desarrollo de ETL
- [x] Envío de ETL a Jhon, con congiguración esperada para el crontab.
- [x] Prueba satisfactoria de ejecución.

**Criterios de aceptación**

- [x] Desarrollo de ETL.
- [x] Prueba de funcionamiento ETL.

**Requerimientos**

- [x] La funcionalidad se encuentra desplegada para release y producción.

**Dependencias**

- bases de datos de cumplidos, argo y agora.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
### ETL reasignación cumplidos ordenadores y supervisores
Se crea el ETL en talend mediante los siguientes scripts:
- Supervisores:
 ```sql
-- bd udistrital_administrativa
select id,numero_contrato,vigencia_contrato,documento_responsable_id,cargo_responsable,fecha_modificacion
from cumplidos.pago_mensual 
where estado_pago_mensual_id=11 and fecha_modificacion IS NOT NULL 
and documento_responsable_id IS NOT NULL 
and cargo_responsable IS NOT NULL;

-- bd udistrital
SELECT  cs.numero_contrato_suscrito numero_contrato, cg.vigencia,sc.dependencia_supervisor
FROM argo.contrato_suscrito cs 
JOIN argo.contrato_general cg ON cg.numero_contrato=cs.numero_contrato 
	LEFT JOIN argo.supervisor_contrato sc ON sc.id=cg.supervisor

select DISTINCT documento, dependencia_supervisor
from argo.supervisor_contrato  where now() between fecha_inicio and fecha_fin order by dependencia_supervisor
 ```
- Ordenadores:
 ```sql
-- bd udistrital_administrativa
select id,numero_contrato,vigencia_contrato,documento_responsable_id,cargo_responsable,fecha_modificacion
from cumplidos.pago_mensual 
where estado_pago_mensual_id=13 and fecha_modificacion IS NOT NULL 
and documento_responsable_id IS NOT NULL 
and cargo_responsable IS NOT NULL and EXTRACT(year from now())= EXTRACT(year from fecha_modificacion)

-- bd udistrital
SELECT  cs.vigencia, cs.numero_contrato_suscrito numero_contrato,  cg.ordenador_gasto
FROM argo.contrato_suscrito cs 
JOIN argo.contrato_general cg ON cg.numero_contrato=cs.numero_contrato 

SELECT o.id_ordenador, o.rol_id FROM  argo.ordenadores o 

SELECT o.documento, o.rol_id FROM  argo.ordenadores o 
where now() between o.fecha_inicio and o.fecha_fin 
```
De igual forma se deja el ejecutable de los Jobs desarrollados por el ingeniero Jhon
[cumplidos_cps.zip](https://github.com/udistrital/cumplidos_cliente/files/11503183/cumplidos_cps.1.zip)

**Comment by JuanCamiloMartinezLopez** [comment]
### Prueba de funcionamiento

Se tomó como prueba el cambio de Decano de la facultad de artes, donde la  anterior decana tenía 1053 cumplidos por revisar.
![MicrosoftTeams-image](https://github.com/udistrital/cumplidos_cliente/assets/42418412/4cb703b9-185c-442f-a12d-1a74c3e85f0f)
De los cuales se reasignaron 227 cumplidos que cumplian con la validacion de fecha de carga.
![MicrosoftTeams-image (1)](https://github.com/udistrital/cumplidos_cliente/assets/42418412/b7240417-e048-4a3f-921f-e61e12e0509e)
