### ISSUE TITLE
Pruebas Funcionales Hito 2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#319]
Se requiere realizar pruebas funcionales de que validen las optimizaciones realizadas.

**Especificaciones técnicas**

- El último desarrollo asociado se encuentra cargado en el repositorio en la rama develop, tanto para el cliente como para el API mid.

**Sub Tareas**

- [x] Desarrollo de pruebas funcionales del cliente y el API mid relacionado con los ajustes de optimización, de acuerdo con el [formato de pruebas](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BFC17015D-62F2-48A6-AF68-56CE53CED926%7D&file=Pruebas%20Funcionales%20-%20CUMPLIDOS.xlsx&action=default&mobileredirect=true&cid=0d67c595-9b19-4d26-b2fe-205b8d9eafb6) dispuesto.
- [x] Corrección de errores o bugs encontrados, que no requieran gran dedicación para su corrección.
- [x] Listado de bugs o errores encontrados que requieran mayor dedicación para su corrección, con una descripción de su posible solución.

**Criterios de aceptación**

- [x] Las funcionalidades del sistema entorno a lo modificado por las optimizaciones se encuentran probadas.
- [x] Los errores que presenta el sistema se encuentran detectados y listados para su corrección.

**Requerimientos**

- [x] El [Issue](https://github.com/udistrital/cumplidos_mid/issues/41) se encuentra terminado.
- [x] Los ajustes de optimización se encuentran desplegados en release

**Dependencias**

- cumplidos_crud
- administrativa_crud_api
- administrativa_amazon_api
- core_amazon_crud
- novedades_mid
- oikos_api
- ruler_api
- financiera_jbpm
- administrativa_jbpm
- titan_api_mid
- documentos_crud
- gestor_documental_mid

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo de pruebas en release.
- [x] Documentación del issue con hallazgos encontrados.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
### pruebas funcionales

Se realizan pruebas funcionales del flujo del sistema en el que se realizaron optimizaciones, dejando evidencia en el siguiente documento:
[Pruebas Funcionales - CUMPLIDOS.xlsx](https://github.com/udistrital/cumplidos_cliente/files/11654401/Pruebas.Funcionales.-.CUMPLIDOS.xlsx)
