### ISSUE TITLE
Restricción de fechas cumplidos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#322]
Restringir la fecha de cumplidos para que no pueda exceder la fecha final del contrato teniendo en cuenta las posibles novedades.

**Especificaciones técnicas**

- El último desarrollo asociado a esta funcionalidad se encuentra en Master.

**Sub Tareas**

- [x] Añadir restricción al calendario desplegado en las fechas de cumplido solicitadas.
- [x] Pruebas locales.

**Criterios de aceptación**

- [x] Ajuste de la restricción propuesta y prueba de funcionamiento.
- [x] Despliegue a dev, release y master.

**Requerimientos**

- [x] La funcionalidad se encuentra desplegada para dev, release y producción.

**Dependencias**

- cumplidos_crud
- administrativa_crud_api
- administrativa_amazon_api
- core_amazon_crud
- novedades_mid
- oikos_api
- ruler_api
- financiera_jbpm
- administrativa_jbpm
- titan_api_mid
- documentos_crud
- gestor_documental_mid

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo y Despliegue Hotfix**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
### Restricción de fechas
Se implementa la restricción de fechas en los inputs de periodo actividades, se toma la fecha de inicio y fin calculada en el endpoint informacion_informe, para el caso de ejemplo el contrato tiene fechas de 2023-01-05 al 2023-08-04, por lo que cualquier fecha fuera de ese rango queda inhabilitada para la selección. 
![image](https://github.com/udistrital/cumplidos_cliente/assets/42418412/af5cb31f-2365-421a-a6c6-32f42ec2dfea)
![image](https://github.com/udistrital/cumplidos_cliente/assets/42418412/d6e663e7-2e22-4e56-8c07-2dc97290b2c8)
