### ISSUE TITLE
Despliegue Hito 4 a producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#323]
De acuerdo con las pruebas realizadas en #311, se requiere realizar la salida a producción, teniendo en cuenta los siguientes requerimientos:

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [x] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2
- [x] Revisión y actualización de variables de entorno
- [x] Pruebas funcionales (grupo de soporte)
- [x] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [x] Pruebas de usuario (Preguntar Revisión SIGUD)
- [x] Pruebas unitarias (equipo de desarrollo)
- [x] Revisión de sincronización de bases de datos en ambientes (prueba y producción)
- [x] Revisión de estado de bases de datos (ETL)
- [x] Revisión de actualización de APIs consumidas (terceros, transversales)
- [x] Definición y/o actualización de manual de usuario/videotutoriales
- [x] Documento de definición de roles y/o accesos

**Comment by JuanCamiloMartinezLopez** [comment]
### documento tecnico
Se agregan la información de la funcionalidad  de reversión
[Descripcion tecnica CUMPLIDOS.docx](https://github.com/udistrital/cumplidos_cliente/files/11763716/Descripcion.tecnica.CUMPLIDOS.docx)

**Comment by milo19980525** [comment]
Se realizó despliegue 7 de julio a las 9:30 pm, se realizaron pruebas funcionales y el sistema quedó estable.

**Comment by JuanCamiloMartinezLopez** [comment]
### Despliegue completo
Se realiza el desligue de forma satisfactoria, se deja evidencia del funcionamiento en producción de la nueva funcionalidad.
![MicrosoftTeams-image](https://github.com/udistrital/cumplidos_cliente/assets/42418412/2b542bb3-da0e-4c0f-b2e6-d6381f1f190a)
