### ISSUE TITLE
Revisión propuesta de formato informe de cumplimiento y de gestión

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#334]
Se requiere pesentar una propuesta para el formato de informe de gestión y cumplimiento que tenga en cuenta las novedades que presenta el contratista y dicha solicitud de pago.

**Especificaciones técnicas**

- El último formato de informe de gestión y cumplimiento se encuentra en el sistema de cumplidos CPS tanto en la rama release como master.

**Sub Tareas**

- [x] Análisis sobre la obtención y presentación de novedades en el informe.
- [x] Presentar mockup (PDF) dónde se presenten diferentes ejemplos de novedades asociadas a un contratista.

**Criterios de aceptación**

- [x] Actualización del issue con los mockups diseñados.
- [ ] 
**Requerimientos**

- ninguno.

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
### Propuesta sección novedades
Se propone crear una tabla que contenga el histórico de todas las novedades post contractuales del contrato y que muestre la información pertinente de cada una de las novedades según su tipo
[PEI-PR-003-FR-009.xlsx](https://github.com/udistrital/cumplidos_cliente/files/11819137/PEI-PR-003-FR-009.xlsx)
![image](https://github.com/udistrital/cumplidos_cliente/assets/42418412/7c2edd0b-9ba3-4f79-9d0d-1150f7f066fd)
