### ISSUE TITLE
Corrección pruebas de carga y seguridad Hito 4

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#339]
Se requiere revisar los puntos referidos por el área de seguridad de la OAS:

**Especificaciones técnicas**

- El último desarrollo funcional se encuentra en la rama release.
- El resultado de las pruebas se encuentra en: https://udistritaleduco-my.sharepoint.com/:w:/r/personal/mfavendannom_udistrital_edu_co/_layouts/15/doc.aspx?sourcedoc=%7B022ffdd9-062b-4d25-8742-484ea16a11ab%7D&action=edit

**Sub Tareas**

- [x] Revisar los campos de "FechaCreacion" quedan sin fecha definida en la siguiente [imagen](https://udistritaleduco-my.sharepoint.com/:i:/g/personal/cerochac_udistrital_edu_co/EQZfHeMLSJ9Pk7oCSEjk6ZABfsejABe3FO5Pt6icksL66Q?e=78BvYa)
- [x] Para el formulario de Reversión de cumplidos aprobados, agregar mensaje de información al usuario final indicando que: “Los cumplidos mostrados no tienen orden de pago y han sido aprobados en los últimos 15 días”.

**Criterios de aceptación**

- [x] Revisión y corrección de la fecha de creación de solicitudes de pago.
- [x] Evidencia del aviso que aclare cuales son los cumplidos que se pueden reversar.

**Requerimientos**

- [x] ninguno.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
Se agrega un texto explicando las condiciones para revertir un cumplido.
![image](https://github.com/udistrital/cumplidos_cliente/assets/42418412/1b265882-cf3a-42a7-90d0-d477ee30d84e)
