### ISSUE TITLE
Apropiación del sistema Cumplidos

### ISSUE THREAD

**Issue by JuanCamiloMartinezLopez** [udistrital/cumplidos_cliente#356]
Se requiere que los desarrolladores clonen y ejecuten los repositorios principales ( cliente y mid ) de cumplidos para acercarse al sistema y su funcionamiento.

** Especificaciones técnicas** 
- Los repositorios son [cliente](https://github.com/udistrital/cumplidos_cliente) y  [mid](https://github.com/udistrital/cumplidos_mid)
- [Documentacion cumplidos](https://udistritaleduco-my.sharepoint.com/personal/juacmartinezl_udistrital_edu_co/_layouts/15/onedrive.aspx?sw=auth&id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS&listurl=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments&remoteItem=%7B%22mp%22%3A%7B%22webAbsoluteUrl%22%3A%22https%3A%2F%2Fudistritaleduco%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%22%2C%22listFullUrl%22%3A%22https%3A%2F%2Fudistritaleduco%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%2FDocuments%22%2C%22rootFolder%22%3A%22%2Fpersonal%2Fjuacmartinezl%5Fudistrital%5Fedu%5Fco%2FDocuments%2FPROYECTO%20CUMPLIDOS%22%7D%2C%22rsi%22%3A%7B%22listFullUrl%22%3A%22https%3A%2F%2Fudistritaleduco%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%22%2C%22rootFolder%22%3A%22%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20CUMPLIDOS%22%2C%22webAbsoluteUrl%22%3A%22https%3A%2F%2Fudistritaleduco%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%22%7D%7D&view=0) 

**Sub Tareas**

- [x] Clonar repositorios del cliente y mid
- [x] Realizar las instalaciones y ajustes necesarios para ejecutarlos en local.
- [x] Revisar la estructura del código.

**Criterios de aceptación**

- [x] La correcta ejecución y funcionamiento de los proyectos en local.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico/SoSM.

**Comment by faidercamilo26** [comment]
Se realiza la apropiación propia del sistema cumplidos, para esto se clonan los respositorios corresponidentes, como lo son: cumplidos_crud, cumplidos:mid y cumplidos_cliente. 

 Se agregan al crud y al mid las variables de entorno, debido a la falta de VPN no me es posible correr el mid, sin embargo, si es posible correr el crud, se corre el programa y leo completamente el “swagger” que corresponde a la documentación que genera en automático el framework beego. 

 Se corre también el cumplidos_cliente para analizar su estructura base, se revisa a fondo el código para comprender de manera general la estructura del cliente de la aplicación. 

[isue #356.pdf](https://github.com/udistrital/cumplidos_cliente/files/15142837/isue.356.pdf)

**Comment by stevencol** [comment]
Realizada configuración inicial del entorno de desarrollo, incluyendo variables de entorno. Aún pendiente la configuración de VPN para la ejecución adecuada de cumplidos_mid. Confirmado funcionamiento correcto de Swagger.

**Comment by JuanCamiloMartinezLopez** [comment]
Revisada y aprobada.
