### ISSUE TITLE
Ajuste y validación del cliente

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_cliente#50]
Ajustar el cliente para consumir los diferentes servicios de las apis desarrolladas (cumplidos_crud, cumplidos_mid)

**Comment by diagutierrezro** [comment]
Con @anndresfelipe29 se realiza el ajuste del cliente de cumplidos realizando la conexión con el nuevo cliente y el nuevo crud del respectivo sistema, queda pendiente la solicitud de las pruebas funcionales para su completa aprobación.

**Comment by anndresfelipe29** [comment]
El ajuste realizado al cliente consiste en:
- Se cambian los endpoints  que usa el aplicativo para solicitar la información de cumplidos, se venia usando endpoints correspondientes a administrativa _mid y se reemplazaron por endpoints que apuntan a los nuevos esquemas cumplidos_crud y cumplidos_mid.  
- A causa del cambio del punto anterior se precisa la creación de dos nuevos servicios en el proyecto cumplidos_crud_service y cumplidos_mid_service.
![image](https://user-images.githubusercontent.com/30865375/103565699-c1e0f480-4e8e-11eb-993a-70591e4b7636.png)

- Cuando se hace una nueva petición a cumplidos_crud a causa del refactor se recibe una respuesta diferente, ahora la información se encuentra encapsulada dentro de data por lo tanto se cambia esa forma de acceder a la información

**Comment by ddguerra90** [comment]
Se realizaron ajustes al cliente para el despliegue el preproducción y la integración continua, modificando el archivo drone.yml con la ayuda del Ingeniero @jjvargass 

Todos los cambios se ven en el siguiente commit: https://github.com/udistrital/cumplidos_cliente/commit/32c0770af192b9d4d3d95dc406065721727d4afd

![image](https://user-images.githubusercontent.com/31446845/103902999-4f0f8d80-50c9-11eb-8510-40b94535f60d.png)
