### ISSUE TITLE
Manual de usuario

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_cliente#69]
Realizar un manual de usuario mostrando el funcionamiento del sistema y su nueva interfaz de usuario.

**Comment by ddguerra90** [comment]
Se adjunta el instructivo de la anterior fase como referencia

[Instructivo Solicitud Cumplidos - Contratistas2019.pdf](https://github.com/udistrital/cumplidos_cliente/files/5803780/Instructivo.Solicitud.Cumplidos.-.Contratistas2019.pdf)

**Comment by diagutierrezro** [comment]
Se realiza el ajuste del instructivo para la solicitud de cumplidos con el nuevo cliente

[INSTRUCTIVO PARA LA SOLICITUD DE CUMPLIDOS DE CONTRATISTAS.pdf](https://github.com/udistrital/cumplidos_cliente/files/5822067/INSTRUCTIVO.PARA.LA.SOLICITUD.DE.CUMPLIDOS.DE.CONTRATISTAS.pdf)

**Comment by diagutierrezro** [comment]
Se crean dos nuevos instructivos para que se de un correcto uso del aplicativo por parte del supervisor y ordenador del gasto
[INSTRUCTIVO_PARA_APROBACION_O_RECHAZO_DE_CUMPLIDOS_ORDENADOR_DE_GASTO_1 (1).pdf](https://github.com/udistrital/cumplidos_cliente/files/5979213/INSTRUCTIVO_PARA_APROBACION_O_RECHAZO_DE_CUMPLIDOS_ORDENADOR_DE_GASTO_1.1.pdf)
[INSTRUCTIVO_PARA_APROBACION_O_RECHAZO_DE_CUMPLIDOS_SUPERVISOR.pdf](https://github.com/udistrital/cumplidos_cliente/files/5979214/INSTRUCTIVO_PARA_APROBACION_O_RECHAZO_DE_CUMPLIDOS_SUPERVISOR.pdf)
