### ISSUE TITLE
mostrar el menu correspondiente

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/cumplidos_cliente#7]
se requiere poder visualizar el menú del respectivo cliente , ya que actualmente se procure error en el.

El menú debe ser consultado con el modulo de `Configuración` de ser necesario debe construirse el menú allí

**Comment by anlramirezs11** [comment]
http://10.20.0.254/configuracionv2/#/pages/dashboard

**Comment by anlramirezs11** [comment]
Se replica el siguiente menú que estaba implementado en Argo: 
![image](https://user-images.githubusercontent.com/29903400/63450100-e4dc4700-c406-11e9-93d8-30aaf83a580.png)
![image](https://user-images.githubusercontent.com/29903400/63450181-0ccbaa80-c407-11e9-8589-59355e7723a5.png)

Para la aplicación de cumplidos:
![image](https://user-images.githubusercontent.com/29903400/63450226-25d45b80-c407-11e9-902b-f89e9b07eebf.png)
![image](https://user-images.githubusercontent.com/29903400/63450324-603df880-c407-11e9-839b-9e94abb285b4.png)

**Comment by anlramirezs11** [comment]
Los roles que se usan son:
Cumplidos CPS:
- CONTRATISTA
- SUPERVISOR
- ORDENADOR_DEL_GASTO



Cumplidos Docentes: 
* DOCENTE
* COODINADOR
* SUPERVISOR
* DECANO

**Comment by anlramirezs11** [comment]
![image](https://user-images.githubusercontent.com/29903400/63455608-b49aa580-c412-11e9-9d56-1fe39d683bb5.png)

![image](https://user-images.githubusercontent.com/29903400/63456062-b44eda00-c413-11e9-9e81-022e96891187.png)

![image](https://user-images.githubusercontent.com/29903400/63456098-c92b6d80-c413-11e9-880c-c6047dbbadcb.png)
