### ISSUE TITLE
Solicitud y resolución de pruebas de vulnerabilidades del sistema

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_cliente#75]
Realizar la solicitud por tuleap en el sistema de gestion de seguridad para las pruebas de vulnerabilidades del sistema.

**Comment by ddguerra90** [comment]
Solicitud para las pruebas en cumplidos
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=39953

**Comment by ddguerra90** [comment]
Tomar los resultados de las pruebas de pentesting y evaluacion de vulnerabilidades para hacer las correcciones pertinentes en el sistema.

https://drive.google.com/drive/folders/1cQou0ebb4n-qqAntqBCxFDBOVgktSVsE

- [ ] Application Error Disclosure
- [ ] Absence of Anti-CSRF Tokens
- [ ] Cross-Domain JavaScript Source File Inclusion
- [ ] Private IP Disclosure 
- [ ] Dependencias javaScript desactualizadas

**Comment by diagutierrezro** [comment]
### Solución Cross-Domain JavaScript Source File Inclusion
<hr>
Se agregan de manera local los scripts de fontawsome y angular material

![image](https://user-images.githubusercontent.com/38676533/106531022-7173ab80-64bb-11eb-823e-18a948c334f8.png)
![image](https://user-images.githubusercontent.com/38676533/106530951-4f7a2900-64bb-11eb-81f4-4bfa3559afd1.png)

Y se elimina el llamado al script de visjs el cual ya no se usa en el aplicativo
![image](https://user-images.githubusercontent.com/38676533/106530979-602a9f00-64bb-11eb-8c2d-5b867a5f70b5.png)

En el script que se agrega llamado 64b53ddd5b se hace un llamado a otro script llamado stats.js, este llamado genera un error por lo que este script tambien se agrega de manera local

![image](https://user-images.githubusercontent.com/38676533/106531213-ce6f6180-64bb-11eb-8e2e-ad3fbfcc9a15.png)

**Comment by diagutierrezro** [comment]
### Solución Cross-Domain JavaScript Source File Inclusion
<hr>

Las ip se encontraban quemadas en los archivos config.js el cual se usaba anteriormente para generar los menús, estas mismas ip se encontraban en menus.js, que es llamado desde menu.js y este a su vez era usado en el index pero ahora el llamado a menu.js se encuentra comentareado, por lo que se procede a eliminar estos 3 archivos

**Comment by diagutierrezro** [comment]
### Solución Vulnerabilidades de dependencias
<hr>

- Se ejecuta el comando **npm audit fix** para que se corrijan automaticamente la mayor cantidad de dependencias posibles de manera automatica
- Despues de ejecutar npm audit se realiza la actualización de varias dependencias de manera manual ejecutando los siguientes comandos
![image](https://user-images.githubusercontent.com/38676533/106533913-f614f880-64c0-11eb-8055-b4a63a1ec0fc.png)

- Algunas dependencias no se pueden actualizar ya que genera fallos en el sistema al momento de ejecutarlas, estas dependencias son **grunt-contrib-connect** y **grunt-wiredep**

**Comment by ddguerra90** [comment]
Se resuelven las vulnerabilidades que no dañan el funcionamiento del sistema y se comenta sobre el mismo kanban de la solicitud a la espera de una nueva revisión o aprobación para su despliegue.
