### ISSUE TITLE
Ajuste de trazabilidad de cumplidos en tabla cambio_estado_pago

### ISSUE THREAD

**Issue by ddguerra90** [udistrital/cumplidos_cliente#80]
Realizar el ajuste para almacenar la información correctamente en la tabla cambio_estado_pago para la trazabilidad del estado de los cumplidos de un contratista.

- [x] Almacenar el estado del pago al momento de que un contratista envíe los documentos por ser revisados
- [x] Almacenar el estado del pago al momento de ser aprobado/rechazado por un supervisor
- [x] Almacenar el estado del pago al momento de ser aprobado/rechazado por un ordenador de gasto

Información relacionada: https://github.com/udistrital/cumplidos_cliente/issues/10

**Comment by anndresfelipe29** [comment]
## Situación problema
A causa de una reunión con el equipo de soporte se detectaron faltas en la implementación de la tabla de cambio_estado_pago , la cual se encarga de hacer un seguimiento en los cambios de cada pago de la tabla pago_mensual causando una falla en el funcionamiento de la tabla y dando información incompleta.
https://github.com/udistrital/cumplidos_cliente/issues/10

## Análisis del problema
Se analiza el código de la aplicación y se determina una sobrecarga de lógica en el cliente. El cliente realiza múltiples peticiones para lograr el seguimiento de la tabla cambio_estado_pago  en el rol supervisor, y en los otros roles no hay una implementación, esto ocurre a causa de una falla de diseño en la cual no se tuvo en cuenta todos los roles.

## Solución
Se propone ajustar los endpoint post y put de pago_mensual controller para que de manera interna haga automáticamente una transacción la cual genere un nuevo registro de cambio_estado_pago cada vez que se cree un nuevo pago mensual o se modifique uno. 

Los efectos de este cambio reducen un poco la carga lógica del cliente al trasladar esa lógica al microservicio crud de cumplidos, sin embargo se aclara que aun el cliente contiene demasiada lógica que debe ser migrada a los servicios mid y crud de cumplidos.

## Implementación
Se modifican los endpoint post y put de pago mensual en el crud de cumplidos para agregar una transacción que agregue un cambio estado pago por cada creación o cambio de un pago mensual, también se cambia la estructura que reciben estos endpoint por:

Antes se recibía esta estructura:
![image](https://user-images.githubusercontent.com/30865375/107822841-c382bf80-6d4c-11eb-8c47-6912dc6aa6bf.png)

Ahora se recibe esta estructura:
![image](https://user-images.githubusercontent.com/30865375/107822861-cb426400-6d4c-11eb-9eb8-f228f5701f27.png)


También se modifica la lógica del cliente en cada rol, eliminando una petición y cambiando la estructura a pago mensual para que se acople con los cambios realizados al crud.

**Comment by diagutierrezro** [comment]
## Solución en Cliente

Después de la modificación realizada en el CRUD se ajustan las peticiones PUT y POST que realiza el cliente en los siguientes casos:

- El cliente crea una nueva solicitud.
- El cliente envía una solicitud de pago para aprobación por parte del supervisor.
- Aprobación o rechazo de las solicitudes por parte del supervisor y del ordenador.

Al momento de realizar estas peticiones se ajusta la estructura que se envía por parte del cliente para que desde el CRUD se realicen la transacción a la tabla pago_mensual y cambio_estado_pago.

![image](https://user-images.githubusercontent.com/38676533/107823493-e2ce1c80-6d4d-11eb-946d-992260a61106.png)

Anteriormente cuando un cliente creaba o enviaba una solicitud de pago no se veian reflejados estos cambios en la tabla cambio_estado_pago y ahora con este nuevo cambio realizado se lleva un registro total de todo el proceso que se realiza con las solicitudes de pago.

**Comment by anndresfelipe29** [comment]
## Solución en pagos masivos

Se cambia la transacción existente para pagos masivos, y ahora se tiene en cuenta realizar los registros en cambio estado pago para cada cambio en un pago mensual.
![image](https://user-images.githubusercontent.com/30865375/108006708-364c9e80-6fca-11eb-8904-fb8bc641c2d8.png)

Ahora la aprobación masiva de pagos se hace directamente desde el crud y este recibe el siguiente body:
![image](https://user-images.githubusercontent.com/30865375/108006834-790e7680-6fca-11eb-86dd-68ccbff86d65.png)

**Comment by Eduargonzalez** [comment]
En esta Imagen se evidencia el flujo completo del servicio de la trazabilidad de los que intervienen en el flujo de los cumplidos.

![image](https://user-images.githubusercontent.com/51488451/108367214-349bfa00-71c7-11eb-9826-868af0b0bc67.png)

**Comment by Eduargonzalez** [comment]
![image](https://user-images.githubusercontent.com/51488451/108367319-54cbb900-71c7-11eb-9a6f-774217ce8585.png)
