### ISSUE TITLE
disparo del flujo de documentos de nuxeo en el cliente

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/cumplidos_cliente#9]
Debido a un requerimiento que solicita que los cumplidos cargados a la plataforma por parte de los contratistas sean públicos, solo después de que el supervisor lo apruebe.

se quiere disparar un "`flujo`" con el cual después de que el supervisor pruebe los cumplidos estos sean publicados.

**Comment by anlramirezs11** [comment]
Se dispara el flujo basico de nuxeo por medio de la plataforma: 
![image](https://user-images.githubusercontent.com/29903400/64193254-0515f800-ce42-11e9-88dc-78f19ae00999.png)

![image](https://user-images.githubusercontent.com/29903400/64193343-2f67b580-ce42-11e9-9c70-88f6d5f9472c.png)

Documentación relevante: https://doc.nuxeo.com/nxdoc/workflows-jsf-ui/

**Comment by anlramirezs11** [comment]
Documentación sugerida por Jhon: 
* https://doc.nuxeo.com/nxdoc/workflow-task-endpoints/

Mirar específicamente "Parallel Review Example"

**Comment by anlramirezs11** [comment]
Intentando hacer el disparo del flujo llegué a la documentación del API: https://documental.portaloas.udistrital.edu.co/nuxeo/api/v1/doc#!/workflow

**Comment by anlramirezs11** [comment]
Se crea un documento de tipo workflow (solicitud) y se le envía la siguiente petición para iniciar el flujo: 
![image](https://user-images.githubusercontent.com/29903400/64278277-f860d500-cf11-11e9-8e9c-e4076989e00a.png)

**Comment by anlramirezs11** [comment]
Segunda Prueba en el workflow "ParallelDocumentReview"
**POST**
https://documental.portaloas.udistrital.edu.co:443/nuxeo/site/api/v1/id/a7f5b78b-8641-4d01-9b43-31bafadbb107

**Body** 
{
"entity-type":"workflow",
"workflowModelName":"ParallelDocumentReview",
"attachedDocumentIds":["{a7f5b78b-8641-4d01-9b43-31bafadbb107}"]
}

Respuesta: 
https://documental.portaloas.udistrital.edu.co/nuxeo/api/v1/workflow/f3fab14f-ac09-4c22-a912-3a83e5cc1eca
**
![image](https://user-images.githubusercontent.com/29903400/64286158-8b097000-cf22-11e9-951a-1555d000d723.png)
**
_______________________________________________________________________________
Para comprobar si se realizó el disparo se ingresó a nuxeo:

![image](https://user-images.githubusercontent.com/29903400/64286829-dc662f00-cf23-11e9-9ea1-47fa4ea1f8a5.png)

Y efectivamente se inició el flujo "ParallelDocumentReview"


Tarea a realizar es hacer una mapear el flujo que se va hacer en cumplidos con este flujo basico: 
![image](https://user-images.githubusercontent.com/29903400/64287187-ac6b5b80-cf24-11e9-9f0b-4163fe338fc3.png)

**Comment by anlramirezs11** [comment]
esde postman como autenticarse con nuxeo.

**Comment by BOTOOM** [comment]
@anlramirezs11 es necesario saber desde postman como se hacen las peticiones para poder replicar en el api algo similar, no encuentro en el presente issue información sobre ello

**Comment by BOTOOM** [comment]
codigo a probar para el api :

```go

func basicAuth(username, password string) string {
  auth := username + ":" + password
   return base64.StdEncoding.EncodeToString([]byte(auth))
}

func redirectPolicyFunc(req *http.Request, via []*http.Request) error{
 req.Header.Add("Authorization","Basic " + basicAuth("username1","password123"))
 return nil
}

func main() {

  client := &http.Client{
    Jar: cookieJar,
    CheckRedirect: redirectPolicyFunc,
}

req, err := http.NewRequest("GET", "http://localhost/", nil)
    req.Header.Add("Authorization","Basic " + basicAuth("username1","password123"))

    resp, err := client.Do(req)
}

```

**Comment by BOTOOM** [comment]
https://golang.org/pkg/net/http/

basicauth

**Comment by BOTOOM** [comment]
https://blog.dotnetframework.org/2017/08/21/make-an-authenticated-http-get-request-and-parse-json-in-golang/

**Comment by anlramirezs11** [comment]
@BOTOOM  las peticiones que tu me pediste que probara en Postman no estaban relacionanadas con este Issue, estaban relacionadas con metadatos.
